Update probe-rs mentions
probe-rs/vscode pull request #70
Opened 2024-01-12 21:48 UTC by bugadani

This PR modernizes the displayed command suggestions in hints and settings. I've also fixed a few typos and clarified which setting overrides debuggerExecutable

2024-01-12 22:08 UTC, noppej approved these changes
Thanks for doing this. I found one more typo, but other than that, I am good with this.

FYI. You need to manually bump the version number to 0.21.3 if you want this PR to push a new version to the VSCode marketplace.

2024-01-12 22:08 UTC, noppej commented on package.json
> +                                "description": "Optionally onnect to an existing `probe-rs dap-server` session on IP and Port, e.g. '127.0.0.1:50000'",
Missed a typo with 'onnect' :)

2024-01-12 22:11 UTC, noppej requested changes
Let's hold merging this until I can look at why the CI is broken.

2024-01-12 22:28 UTC, Yatekii approved these changes
Thanks!

2024-01-15 14:49 UTC, noppej commented
@bugadani CI is now fixed. Thanks for helping to cleanup the docs/usability issues!

2024-01-15 14:49 UTC, noppej approved these changes

2024-01-15 16:07 UTC, bugadani commented
My pleasure :)

2024-01-15 16:07 UTC, merged